#!/usr/bin/env bash
# This script is displaying "Best School" using a while loop

#On the 9th 9th iteration, displays Best School and then Hi on a new line

count="0"

while [ $count -lt 10 ]
      if [ $count -eq 9 ]
        echo "Hi"

      fi 
       echo "Best School"
          (( count++))
done
