#!/usr/bin/env bash
#displaying numbers from 1 to 20
#displaying "bad luck from china" for the 4th iteration
#displaying "bad luck from japan" for the 9th iteration
#displaying "bad luck from italy" for the 17th iteration

i=1

while [ "$i" -le 20 ]
do 
         echo "$i"
         case $i in
               "4") echo "bad luck from china";;
               "9") echo "bad luck from japan";;
               "17") echo "bad luck from italy";;
         esac
        i=$(( i + 1 ))
done
