#!/usr/bin/env bash
#using thew while loop and case loop to list first 20 numbers

number=1

while [ $number -le 20 ]
do
	case $number in
		
		4)
			echo "$number"
			echo "bad luck from China"
		  ;;
		9)
			echo "$number"
			echo "bad luck from Japan"
		  ;;
		17)
			echo "$number"
			echo "bad luck from Italy"
		  ;;

		*)
		  echo "$number"
		  (($number++))
		  ;;
esac
done
