#!/usr/bin/env bash
#displaying numbers from 1 to 20
#displaying "bad luck from china" for the 4th iteration
#displaying "bad luck from japan" for the 9th iteration
#displaying "bad luck from italy" for the 17th iteration

count=1

while [ $count -le 20 ]
do 
         echo "$count"
         case $count in
               "4") echo "bad luck from china" >&2;;
               "9") echo "bad luck from japan" >&2;;
               "17") echo "bad luck from italy" >&2;;
         esac
	 (( count++ ))
done
