#!/usr/bin/env bash
#Displaying a list of currently running process
# show all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchy

ps -a -x -u -f 

