#!/usr/bin/env bash
# Function to handle signals
signal_handler() {
    case $1 in
        SIGINT)
            echo "Y U no love me?!" ;;
        SIGTERM)
            echo "I hate the kill command" ;;
        SIGQUIT)
            cleanup ;;
    esac
}

# Function to perform cleanup
cleanup() {
    echo "Deleting PID file and terminating"
    rm -f /var/run/myscript.pid
    exit 0
}

# Trap signals and call signal_handler function
trap 'signal_handler SIGINT' SIGINT
trap 'signal_handler SIGTERM' SIGTERM
trap 'signal_handler SIGQUIT' SIGQUIT

# Write PID to file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
echo "To infinity and beyond"
while true; do
    sleep 1
    echo "To infinity and beyond"
done
