#!/bin/bash

case "$1" in
    start)
        /bin/bash /path/to/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -e /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -e /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            /bin/bash /path/to/manage_my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process restarted"
        else
            /bin/bash /path/to/manage_my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
